
DESIGN_NAME: frv_8
VERILOG_FILES: dir::frv_8_nl.sv
CLOCK_PORT: clk_i
CLOCK_PERIOD: 10 # 10ns = 100MHz

FP_SIZING: relative
#DIE_AREA: [0, 0, 50, 50]
PL_TARGET_DENSITY_PCT: 60

VDD_NETS:
- VDD
GND_NETS:
- VSS

# Reduce wasted space
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6